### ISSUE TITLE
Error with loading NetBox

### ISSUE THREAD

**Issue by Dehalion** [aloneguid/storage#103]
Hi!

As soon as I install Storage.Net into my project and use IBlobStorage somewhere I get

> Could not load file or assembly 'NetBox' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

What could be the problem?

**Comment by aloneguid** [comment]
Nope, running it right now with no issues.

**Comment by Dehalion** [comment]
Thanks for the quick response. I've tried again with cleaned NuGet cache and manually deleted packages and bin/obj folders. Here are some more details:

Web, BusinessLogic and UnitTest projects using .NET 4.7.2
Restored all NuGet packages, installed Storage.Net 7.1.17 and NetBox 2.3.4 from NuGet to the BusinessLogic project.

The Web project fails to start with the given error as soon as I have an IBlobStorage field in the BusinessLogic (no matter if it is used or not). Unit tests run fine though 🤷‍♂ 

It seems I've run into a very specific conflict in my Web project. Any ideas other than start over with a new project or write my own file abstraction?

**Comment by aloneguid** [comment]
Maybe attach a zip with sample solution here which reproduces the problem, I can have a look.

**Comment by Dehalion** [comment]
Ok, I've now reduced my solution to the relevant files.
[MySolution.zip](https://github.com/aloneguid/storage/files/3456416/MySolution.zip)

The `FileStorageBusinessLogic` in the `MyBusinessLogic` project uses _Storage.Net_.
The unit test using it passes, the `MyWeb` project fails with given error if started.

If you remove any usage of _Storage.Net_ (eg. comment all code in `FileStorageBusinessLogic`, at least every reference to `IBlobStorage` and `StorageFactory`), the `MyWeb` project can be run and renders "Hello!".

**Comment by aloneguid** [comment]
Thanks, found the problem in aloneguid/support#9, will re-release in a few minutes.

**Comment by aloneguid** [comment]
Fixed in 7.1.19

**Comment by Dehalion** [comment]
Great, now it works. Thanks for the quick response.
