### ISSUE TITLE
AWS: can't use assumed roles / environment settings with connection strings

### ISSUE THREAD

**Issue by jonscheiding** [aloneguid/storage#104]
Currently, `AwsStorageModule` requires the `keyId` and `key` parameters to construct a storage adapter from a connection string.  It would be nice to be able to use ambient authentication information, such as EC2/Lambda IAM roles or environment variable configuration.

**Comment by aloneguid** [comment]
Good idea, happy for you to pick this up.

**Comment by aloneguid** [comment]
closing as resolved
