### ISSUE TITLE
File encoding on WriteAsync

### ISSUE THREAD

**Issue by maQus123** [aloneguid/storage#118]
When using `_storage.WriteAsync("file with special charäcters.txt", bytes);` to upload a file to a disk directory the file is uploaded successfully but is named `file+with+special+char%C3%A4cters.txt`. I tried arround with `HttpUtility.UrlEncode` but couldn't get it working. What do I miss? Do you have a tip? Thx :)

**Comment by aloneguid** [comment]
I've noticed that recently too,  will fix it on Monday ;)

**Comment by maQus123** [comment]
@aloneguid Any news on this?

**Comment by aloneguid** [comment]
it's fixed a while ago, forgot to comment here, please check

**Comment by maQus123** [comment]
@aloneguid Sorry but unfortunately cannot check it because I ended up building my own storage abstraction based on native Azure Blob SDK and `System.IO.Directory` / `System.IO.File` for file share UNC support. I needed the flexibility. But generally, your library is awesome. Really appreciate your work, thank you very much for your effort to open source :-)

**Comment by aloneguid** [comment]
thank you ;)
