### ISSUE TITLE
How to create a folder using AmazonS3BlobStorage?

### ISSUE THREAD

**Issue by jrlichina** [aloneguid/storage#126]
Hello,

I was able to create/read/write/list files successfully but I can't seem to figure out how to create an empty folder.

**Comment by aloneguid** [comment]
Hi. AWS S3 doesn't have a concept of a folder, see https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html

**Comment by jrlichina** [comment]
Thank you!
