### ISSUE TITLE
One time download link (GetReadOnlySasUriAsync) removed

### ISSUE THREAD

**Issue by jbbos** [aloneguid/storage#128]
In commit abe43d2ade71c0230918fb18db04a01f75d4c07d in file [IAzureBlobStorage.cs](https://github.com/aloneguid/storage/blob/abe43d2ade71c0230918fb18db04a01f75d4c07d/src/Azure/Storage.Net.Microsoft.Azure.Storage/Blobs/IAzureBlobStorage.cs) "GetReadOnlySasUriAsync" was changed to "GetContainerSasAsync" or at least the first one was removed and the other one added. I found it useful to create one time download links which did not grant access to the whole container. Unfortunately I can't use the new version because of this yet. This change was done the same way in the interface as well as in the test.

IAzureBlobStorage.cs
https://github.com/aloneguid/storage/commit/abe43d2ade71c0230918fb18db04a01f75d4c07d#diff-d7932b339e077b0447c489bfcb896810

LeakyAzureBlobStorageTest.cs
https://github.com/aloneguid/storage/commit/abe43d2ade71c0230918fb18db04a01f75d4c07d#diff-9ed2ea6379646cde530f882a26e16ade

**Comment by aloneguid** [comment]
Please have a look [here](https://github.com/aloneguid/storage/blob/master/doc/blobs/azure.md#blob).

**Comment by jbbos** [comment]
Thanks, great!
