### ISSUE TITLE
Support of Azure Cosmos DB

### ISSUE THREAD

**Issue by tweeren** [aloneguid/storage#138]
Can you add in support for Azure Cosmos DB?
Although Cosmos DB and Table Storage uses the same API, current method of connecting using just the account and key is insufficient to create the connection to Cosmos DB.
Need to add in a new parameter "TableEndpoint".

**ConnectionString sample for CosmosDB:**
DefaultEndpointsProtocol=https;AccountName=<acc_name>;AccountKey=<acc_key>;TableEndpoint=https://<acc_endpoint>.table.cosmos.azure.com:443/;

**ConnectionString sample for Table Storage:**
DefaultEndpointsProtocol=https;AccountName=<acc_name>;AccountKey=<acc_key>;EndpointSuffix=core.windows.net

Alternatively is to allow the use of the entire connection string, instead of extracting the account value and key value.

**Comment by aloneguid** [comment]
Hi @tweeren unforunately since v9 key-value support was dropped. There is simply too much variance between different implementations to make it truly useful.
