### ISSUE TITLE
Storage.Net.Microsoft.Azure.Storage nuget v9

### ISSUE THREAD

**Issue by mariopasquali** [aloneguid/storage#165]
Hi, just started using this project to support Azure / AWS / GCP blob storage.  I am running into an FileLoadException when I put .UseAzureStorage.  I think this is because Storage.Net.Microsoft.Azure.Storage is based on v8 and the others are based on v9.  Is there a plan to release an updated nuget for this package?  Or maybe I am not using the right one for Azure support?

**Comment by aloneguid** [comment]
Hey you're right, try using Storage.Net.Microsoft.Azure.Storage.Blob, that one is targeting v9 and latest azure SDK.

**Comment by mariopasquali** [comment]
Hi Ivan, thank you for the quick turnaround, much appreciated.  You might wish to update the following page pointing to the legacy package name:
https://github.com/aloneguid/storage/blob/develop/doc/blobs/azure.md
