### ISSUE TITLE
question: release cycle

### ISSUE THREAD

**Issue by Ne4to** [aloneguid/storage#183]
What is the release cycle of the NuGet package to nuget.org?
The latest release was 5 months ago and now `master` is 53 commits behind `develop`.
I would like to use the latest fix in `develop` branch. 
The readme.md says that I can use `https://pkgs.dev.azure.com/aloneguid/AllPublic/_packaging/storagenet/nuget/v3/index.json` feed for `develop` branch, but it is unavailable: `{"$id":"1","innerException":null,"message":"The feed with ID 'storagenet' doesn't exist.","typeName":"Microsoft.VisualStudio.Services.Feed.WebApi.FeedIdNotFoundException, Microsoft.VisualStudio.Services.Feed.WebApi","typeKey":"FeedIdNotFoundException","errorCode":0,"eventId":3000}`

**Comment by aloneguid** [comment]
There's no specific release cycle, I'm trying to release as soon as there is enough features, but haven't been on this project for a few months due to other arrangements. Master is now up to date with develop.

I think preview nuget feed is broken, something to fix.
