### ISSUE TITLE
ListOptions does not support Marker or other more advanced concepts, is too simple to use in complex projects

### ISSUE THREAD

**Issue by Cloudmersive** [aloneguid/storage#193]
When you have millions (or billions) of blobs, you need more advanced options for enumerating them.  For example, S3 has a concept of a Marker which can help you get all of the blobs that were created after the last query.  Or the ability to define queries on attributes such as creation date time are also critical.

Unfortunately, ListOptions does not provide this functionality and so means Stoage.net cannot be used for high scale projects.

**Comment by aloneguid** [comment]
I am using it in a couple of high scale projects 😂
