### ISSUE TITLE
Connection string parsing problem: '+' symbol inside key

### ISSUE THREAD

**Issue by zvasilius** [aloneguid/storage#227]
In case of connection string using for Azure Storage, for example

var connectionString ="azure.blob://account=...;key=dBg70y4GvGH8FGEX3pQDL8NUjCif8sFzHoIMQtfhyt1lAwRlZSMG05/fhBskSBCk7Kcp1b/yNEet+AStPm+WJQ==";
StorageFactory.Blobs.FromConnectionString(connectionString); 

throws next error:

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

This happens because 'UrlDecode' replaces '+' symbols in StorageConnectionString:

                        foreach (string str in connectionString.Split(PartsSeparators, StringSplitOptions.RemoveEmptyEntries))
                        {
                            string[] strArray = str.Split(PartSeparator, 2);
                            this._parts[strArray[0]] = (strArray.Length == 1 ? string.Empty : strArray[1]).UrlDecode();
                        }
But the same credentials works fine if to use it in regular way:

StorageFactory.Blobs.AzureBlobStorageWithSharedKey("...", dBg70y4GvGH8FGEX3pQDL8NUjCif8sFzHoIMQtfhyt1lAwRlZSMG05/fhBskSBCk7Kcp1b/yNEet+AStPm+WJQ==");

Any ideas?

**Comment by DavidInterad** [comment]
This was already brought up in #173 
It seems this is intended behaviour, you should replace + with %2B for it to work.

**Comment by zvasilius** [comment]
Thank you, @DavidInterad, it helped.
