### ISSUE TITLE
AWS S3 API against other services

### ISSUE THREAD

**Issue by LordMike** [aloneguid/storage#33]
The S3 API is becoming very popular for other third parties, such as [Minio](https://www.minio.io/).

It could be great, if the AWS S3 storage api could add an option to provide the URL to a third party service. Other considerations include: Validating certificates (might be self signed certs), supporting arbitrary ports and so on.

**Comment by nelfer** [comment]
This would be great! I'm working on a system to provide cloud storage and it seems like Storage.Net will work, but for local (and I don't mean disk) we would have to use something else.

**Comment by LordMike** [comment]
"On premise" is what you're looking for.

**Comment by nelfer** [comment]
Yes. Being able to use on premise object storage would be great. I just learned also that DigitalOcean object storage (seems to) uses the AWS S3 API as well.

**Comment by aloneguid** [comment]
Can this be done with an official AWS S3 SDK?

**Comment by LordMike** [comment]
https://github.com/minio/cookbook/blob/master/docs/aws-sdk-for-dotnet-with-minio.md

**Comment by nelfer** [comment]
Yes @aloneguid the AWS SDK allows to specify the end point URL.

**Comment by aloneguid** [comment]
It shouldn't be hard to add then. Would you like to raise a PR?
