### ISSUE TITLE
AwsS3BlobStorageProvider.Initialise method passes silently when AmazonS3Exception ex thrown

### ISSUE THREAD

**Issue by sanan-fataliyev** [aloneguid/storage#40]
https://github.com/aloneguid/storage/blob/ad8c2adc4256f517cf86ebe8ad8809b49ed6ee9a/src/Storage.Net.Amazon.Aws/Blob/AwsS3BlobStorageProvider.cs#L78-L81

**Comment by aloneguid** [comment]
The error happens when you're trying to create a bucket which already exists, it is expected.

**Comment by sanan-fataliyev** [comment]
Okay, but when the errorCode isn't "BucketAlreadyOwnedByYou", then we shouldn't throw actual exception?

**Comment by sanan-fataliyev** [comment]
Like
```
if(ex.ErrorCode != "BucketAlreadyOwnedByYou") 
{ 
    throw ex;
} 
````
