### ISSUE TITLE
Run-time exception "Could not load type 'Storage.Net.Blob.AsyncBlobStorage'"

### ISSUE THREAD

**Issue by AlexandrSymonov** [aloneguid/storage#49]
Exception:
`
Run-time exception (line 8): Could not load type 'Storage.Net.Blob.AsyncBlobStorage' from assembly 'Storage.Net, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8dea52f811e261ef'.

Stack Trace:

[System.TypeLoadException: Could not load type 'Storage.Net.Blob.AsyncBlobStorage' from assembly 'Storage.Net, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8dea52f811e261ef'.]
   at Storage.Net.Factory.AzureBlobStorage(IBlobStorageFactory factory, String accountName, String key, String containerName)
   at Program.Main() :line 8
`

![image](https://user-images.githubusercontent.com/45991569/50352587-55685680-054e-11e9-8728-dc3132ece196.png)

**Comment by AlexandrSymonov** [comment]
Hi, @aloneguid, Could you help me with this?

**Comment by aloneguid** [comment]
You might want to provide more information, there is nothing I can help with having just that.
