### ISSUE TITLE
Use Database as KeyValueStore

### ISSUE THREAD

**Issue by michaelrall** [aloneguid/storage#82]
Hello,

are there any concerns to implement a DB based Provider for KeyValue Stores? What would be a good choice for the DB Access Framework (EF core)?

cheers Michael

**Comment by aloneguid** [comment]
Hey, good question. We had one before, however it didn't work out very well. It's not always possible to map a Value to database row, as they are not strongly typed unlike database rows. EF Core is a much better choice for those scenarios. You could always use database as a fake provider and have only two columns - key and value, however I'm not sure how helpful it would be (there are cheaper and better ways to store key-values comparing say SQL server).

**Comment by michaelrall** [comment]
Yeah, I see your point. I'll have a look at your existing MSSQL-Provider and maybe your settings-framework targets my needs better (especially through combining it with NET.storage :-) )

**Comment by aloneguid** [comment]
Feel free to share it here, it's the people like you who make this library useful! ;)
