### ISSUE TITLE
Add .NET Standard 2.0 TF to all packages to simplify dependencies

### ISSUE THREAD

**Issue by RicoSuter** [aloneguid/storage#86]
From https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target

> ... we recommend that you also target .NET Standard 2.0. This simplifies the dependency graph for users of your library that run on .NET Standard 2.0 compatible frameworks, and it reduces the number of packages they need to download.

Should be quite a simple change and will should not break users.

**Comment by aloneguid** [comment]
Yes, v7 branch already addresses this. It's either .net standard 1.6 or 2.0 depending how low we can go. .NET Framework explicit dependency is going away, the primary reason was low usage and inability to utilise linux based build servers.

**Comment by aloneguid** [comment]
Try the prerelease packages on Nuget, see when you think.

**Comment by RicoSuter** [comment]
> It's either .net standard 1.6 or 2.0

It should always have .net standard 2.0 and if possible also an additional lower .net standard...

**Comment by aloneguid** [comment]
What's the reason for targeting 2.0 when already targeting 1.6?

**Comment by RicoSuter** [comment]
From the link: 

> If your project targets .NET Standard 1.x, we recommend that you also target .NET Standard 2.0. This simplifies the dependency graph for users of your library that run on .NET Standard 2.0 compatible frameworks, and it reduces the number of packages they need to download.

The reason for this recommendation is that with .net standard 1.x they tried to deliver everything in packages (e.g. tons of these System.* packages) - they (Microsoft) found out that this is not feasible (i.e. too slow) and with .net standard 2.0 you just have all these dependencies implicitly... that's why Microsoft recommends to always also add the 2.0 target to simplify deps, restore etc.

Some screenshots: https://github.com/Picturepark/Picturepark.SDK.DotNet/issues/171

**Comment by aloneguid** [comment]
Got it, makes perfect sense.

**Comment by RicoSuter** [comment]
BTW: I can help you with this library with PRs because I really like the concept and also the implementation. I think it is essential in cloud apps/microservices to quickly try out different services etc. migrate to different clouds etc.

**Comment by aloneguid** [comment]
@RicoSuter I'd really appreciate that!

**Comment by aloneguid** [comment]
There are a lot of improvements/new stuff coming in V7 (branch here). Also there is a new project running (private repo so far) that uses storage.net to manipulate any storage visually, some spoilers:

![image](https://user-images.githubusercontent.com/3155189/60621537-d8a81600-9dd5-11e9-8d55-f0e4a3406e09.png)

**Comment by aloneguid** [comment]
so stuff like this is possible (azure blob storage in this case) https://www.screencast.com/t/beAqLnH5AuCU

**Comment by RicoSuter** [comment]
Nice, this is UWP, right?

Ill play a bit with the v7 libs tomorrow and try to migrate an app. Maybe i’ll come up with more proposals 😏

**Comment by aloneguid** [comment]
It's WPF running on .NET Core 3 Preview 6, early days but impressive and blazing fast!

**Comment by aloneguid** [comment]
This is fixed now.
