### ISSUE TITLE
Allow cancellation of message processing function

### ISSUE THREAD

**Issue by RicoSuter** [aloneguid/storage#87]
The `onMessageAsync` is currently a function which does not take the cancellation token: 

```
Task StartMessagePumpAsync(Func<IReadOnlyCollection<QueueMessage>, Task> onMessageAsync, ..., CancellationToken cancellationToken)
```

Wouldn't it be better if it would pass in the received CT? i.e. use 

```
Func<IReadOnlyCollection<QueueMessage>, CancellationToken, Task> onMessageAsync
```

https://github.com/aloneguid/storage/blob/master/src/Storage.Net/Messaging/IMessageReceiver.cs#L38

This might be required to quickly shut down a process - a message processing might take multiple minutes and thus it also should be cancellable. If a message processing is cancelled then it is either not commited and/or rolled back (i.e. goes back to the queue)

**Comment by aloneguid** [comment]
Agree, makes perfect sense, CT can be populated deeper.

**Comment by aloneguid** [comment]
released in nuget
